---
- name: Install jenkins
  hosts: all
  become: yes
  become_user: root



  tasks:
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    - name: Download jenkins key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: jenkins
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins.list

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
    
    - name: Install fontcongig
      shell: apt install fontconfig -y


    - name: Install java
      shell: apt install fontconfig openjdk-17-jre -y


    - name: Install the jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Make sure a service unit is running
      ansible.builtin.systemd_service:
        state: started
        name: jenkins
        enabled: yes

