---
- name: Install SonarQube with Docker
  hosts: all
  become: yes
  tasks:
    # Install required dependencies
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    # Add Docker's official GPG key
    - name: Add Docker's GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Add Docker repository
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    # Install Docker
    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    # Install Docker Compose
    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-{{ ansible_system | lower }}-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    # Create directories for SonarQube setup
    - name: Create directories for Docker Compose
      file:
        path: "/opt/sonarqube/{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - data
        - logs
        - extensions

    # Create Docker Compose file
    - name: Create docker-compose.yml for SonarQube
      copy:
        dest: /opt/sonarqube/docker-compose.yml
        content: |
          version: "3.8"

          services:
            sonarqube:
              image: sonarqube:community
              container_name: sonarqube
              ports:
                - "9000:9000"
              environment:
                - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
                - SONAR_JDBC_USERNAME=sonar
                - SONAR_JDBC_PASSWORD=sonar
              depends_on:
                - db
              volumes:
                - sonarqube_data:/opt/sonarqube/data
                - sonarqube_logs:/opt/sonarqube/logs
                - sonarqube_extensions:/opt/sonarqube/extensions

            db:
              image: postgres:14
              container_name: sonarqube_db
              environment:
                POSTGRES_USER: sonar
                POSTGRES_PASSWORD: sonar
                POSTGRES_DB: sonarqube
              volumes:
                - postgresql_data:/var/lib/postgresql/data

          volumes:
            sonarqube_data:
            sonarqube_logs:
            sonarqube_extensions:
            postgresql_data:

    # Start SonarQube with Docker Compose
    - name: Start SonarQube
      command: docker-compose up -d
      args:
        chdir: /opt/sonarqube

